apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-public-home-lab
  namespace: cloudflare
data:
  config.yaml: |
    tunnel: public-home-lab
    credentials-file: /etc/cloudflared/credentials/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
